version: '3.7'

services:
  server:
    build:
      context: ./Back_Cash_Manager
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/app/data

  mobile:
    build:
      context: ./CashManagerFront
    volumes:
      - shared_data:/app/data
    command: sh -c "./gradlew clean assembleDebug"

volumes:
  shared_data:
